### ISSUE TITLE
Compile and Run C++ Code Through CMD

### ISSUE THREAD

**Issue by arslanaslam007** [aneesbazmi/FinalYearProject#4]
I have Successfully Compiled and Run C++ Code in C#...

I am Using Visual Studio 2013.
C++ Source Code FileName is "hello.cpp" present in D drive.
here is my Code

        Process process = new System.Diagnostics.Process();

        ProcessStartInfo startInfo = new System.Diagnostics.ProcessStartInfo();
        startInfo.FileName = "cmd.exe";
        startInfo.Arguments = "/K \"C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\vcvarsall.bat\" && dir";
        startInfo.RedirectStandardInput = true;
       // startInfo.RedirectStandardOutput = true;
        startInfo.UseShellExecute = false;

        process.StartInfo = startInfo;
        process.Start();

        process.StandardInput.WriteLine("d:");
        process.StandardInput.WriteLine("cl /EHsc hello.cpp");
        process.StandardInput.WriteLine("hello.exe");

        process.WaitForExit();
        process.Close();

**Comment by arslanaslam007** [comment]
https://www.youtube.com/watch?v=0wjnt3y4oDM
the above video shows the compilation of c++ code file from Developer Command Prompt VS2015

**Comment by arslanaslam007** [comment]
Command used to Compile C++ Code is
cl /EHsc mycode.cpp

Command used to Run C++ Code is
mycode.exe

**Comment by arslanaslam007** [comment]
When a program is submitted to server side
these are the following steps will be performed in our application

if program is not compiled than error of compilation will be returned to the user

![compile and run](https://user-images.githubusercontent.com/40546956/46616708-94ccfc80-cb34-11e8-8de8-18a443c322c1.PNG)


Result of each matching will be stored in Array-Structure

**Failure Scenario**

There are Five types of Errors Expected during test case matching

1. Runtime Error
2. Time Limit Error
3. Input Output Mismatch Error

**Comment by arslanaslam007** [comment]
Compiling C++ Code in C# Environment

Source

https://www.codeproject.com/Articles/10324/Compiling-code-during-runtime
https://stackoverflow.com/questions/19730548/c-c-code-compiler-in-c-sharp
https://stackoverflow.com/questions/23543134/how-to-compile-c-code-using-c-need-to-develop-a-c-ide
https://stackoverflow.com/questions/23553159/how-to-compile-c-code-using-cppcodeprovider-in-c-sharp

**Comment by arslanaslam007** [comment]
As Discussed today , we have to give input and output to program through file.

Let me show you how we will do it from start.



Problem statement 
"Take input two integer from user and display their result"

Test Case
![test](https://user-images.githubusercontent.com/40546956/46676805-b395c680-cbfa-11e8-8e7f-5581a57ef0a2.PNG)


Code Submitted to Server Side

#include <iostream>
using namespace std;

int main ()
{
	int a,b;

	cin>>a;
	cin>>b;
	
	cout<<a+b;

	return 1;
}
 
On server side there will be following files
![start](https://user-images.githubusercontent.com/40546956/46677020-2d2db480-cbfb-11e8-8de4-d40c1be1720b.PNG)

Code.cpp represent user submitted Code as discussed above

test.txt represent test case for checking the program
its content will be 
5
10

trueout.txt represent correct output for test case as discussed above 
its content will be 
15

userout.txt represent output fro user code for test case 

result.txt will contain result whether _userout.txt matches matches the trueout.txt_ 

To compile and Run the Program through CMD will be as
![cmd](https://user-images.githubusercontent.com/40546956/46677810-bd202e00-cbfc-11e8-9655-de547d9f761c.PNG)


Now compare userout.txt with trueout.txt and store in result.txt 

![1](https://user-images.githubusercontent.com/40546956/46678271-b3e39100-cbfd-11e8-8c5d-c50cd853fedd.PNG)

content of result.txt will be asa

Comparing files userout.txt and TRUEOUT.TXT
FC: no differences encountered

result.txt will be returned to the client side

All of above thing can be done in c# as
![c](https://user-images.githubusercontent.com/40546956/46678673-94009d00-cbfe-11e8-9386-bebd045b564c.PNG)

**Comment by aneesbazmi** [comment]
i compiled, run and executed hello.cpp on some inputs
stored its output in result.txt
compared and theennnnnnnn compared file etc......
